config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "pages#home"

  get "contact", to: 'pages#contact', as: "contact"
  get "inspiration", to: 'pages#inspiration', as: "inspiration"

  get "privacy", to: 'pages#privacy', as: "privacy"
  get "returnpolicy", to: 'pages#returnpolicy', as: "returnpolicy"
  get "sitemap", to: 'pages#sitemap', as: "sitemap"



  resources :paintings do
    resources :reviews, only: [:new, :create]
    resources :orders, only: [:new, :create, :edit, :update, :show] do
      resources :payments, only: [:new, :create]
    end
    # get ''
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

  resources :addresses, only: [:new, :create, :destroy]
  resources :shipping_addresses, only: [:new, :create, :destroy]
  resources :contacts, only: [:new, :create]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/painting.rb
class Painting < ApplicationRecord
  has_many :reviews
  has_one :order
  monetize :price_cents
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  # skip_before_action :authenticate_user!

  def index
    @paintings = Painting.all
    @paintings_abstract = Painting.all.where("category = ?", "Abstract")
    @paintings_figurative = Painting.all.where("category = ?", "Figurative")
    @paintings_portrait = Painting.all.where("category = ?", "Portrait")
    @paintings_other = Painting.all.where("category = ?", "Other")
  end

  def show
    @painting = Painting.find(params[:id])
    # @order_item = current_order.order_items.new
    @review = Review.new
    @order = Order.new
    @address = Address.new
  end

  private

  def article_params
    params.require(:painting).permit(:name, :description, :year, :price, :photo)
  end
end

app/views/paintings/index.html.erb
<div class="index-intro">
  <h2 class="main-subtitle">Shop</h2>
  <br>
  <p class="main-text">
  As a self represented artist I offer my work for purchase directly from my studio.
  </p>

  <p class="main-text">
  For all purchases via my site you get a <strong>FREE WORLDWIDE SHIPPING</strong> and a <strong>30 DAYS MONEY-BACK GUARANTEE</strong>.
  </p>

  <p class="main-text">
  All orders are shipped within 5 days. Please, consider my refund policy in the footnote of this page.
  </p>
</div>

<div class="categories">
<div class="category-cards">

  <div class=" abstractcat">
      <div class="category-text">
        <h3> ABSTRACT</h3>
      </div>
  </div>

  <div class=" figurativecat">
      <div class="category-text">
        <h3>FIGURATIVE</h3>
      </div>
  </div>

  <div class=" portraitcat">
      <div class="category-text">
        <h3>PORTRAIT</h3>
      </div>
  </div>

  <div class=" othercat">
      <div class="category-text">
        <h3>OTHER</h3>
      </div>
  </div>

</div>
</div>

<div class="paintings">

  <div class="all-paintings">
     <% if @paintings %>
        <% @paintings.each do |painting| %>
         <%= link_to painting_path(painting) do %>
          <div class="card-painting">
            <%#= image_tag("Alex-2014.jpg") %>
            <%= image_tag painting.photo, crop: :fill%>
            <div class="card-painting-infos">

                <h3><strong><%= painting.name %></strong> (<%= painting.year %>)</h3>
                <p><%= humanized_money_with_symbol(painting.price) %></p>
                <p><%= painting.height %>cm x <%= painting.width %>cm.
                <p><%= painting.description.truncate_words(10) %></p>
            <!--   <h2 class="card-painting-pricing"><%#= abs_painting.price %></h2> -->
            </div>
          </div>
          <% end %>
        <% end %>
      <% end %>
    </div>



  <div class="abstract-paintings d-none">
   <% if @paintings_abstract %>
      <% @paintings_abstract.each do |abs_painting| %>
       <%= link_to painting_path(abs_painting) do %>
        <div class="card-painting">
          <%#= image_tag("Alex-2014.jpg") %>
          <%= image_tag abs_painting.photo, crop: :fill%>
          <div class="card-painting-infos">

              <h3><strong><%= abs_painting.name %></strong> (<%= abs_painting.year %>)</h3>
              <p><%= humanized_money_with_symbol(abs_painting.price) %></p>
              <p><%= abs_painting.height %>cm x <%= abs_painting.width %>cm.
              <p><%= abs_painting.description.truncate_words(10) %></p>

          <!--   <h2 class="card-painting-pricing"><%#= abs_painting.price %></h2> -->
          </div>
        </div>
        <% end %>
      <% end %>
    <% end %>
  </div>


  <div class="figurative-paintings d-none">
    <% if @paintings_figurative %>
      <% @paintings_figurative.each do |fig_painting| %>
        <%= link_to painting_path(fig_painting) do %>
          <div class="card-painting">
            <%#= image_tag("Alex-2014.jpg") %>
            <%= image_tag fig_painting.photo, crop: :fill %>
            <div class="card-painting-infos">

                <h3><strong><%= fig_painting.name %></strong> (<%= fig_painting.year %>)</h3>
                <p><%= humanized_money_with_symbol(fig_painting.price) %></p>
                <p><%= fig_painting.height %>cm x <%= fig_painting.width %>cm.
                <p><%= fig_painting.description.truncate_words(10) %></p>

              <!-- <h2 class="card-painting-pricing"><%= fig_painting.price %></h2> -->
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>


  <div class="portrait-paintings d-none">
    <% if @paintings_portrait %>
      <% @paintings_portrait.each do |portrait_painting| %>
        <%= link_to painting_path(portrait_painting) do %>
          <div class="card-painting">
            <%#= image_tag("Alex-2014.jpg") %>
            <%= image_tag portrait_painting.photo, crop: :fill %>
            <div class="card-painting-infos">

                <h3><strong><%= portrait_painting.name %></strong> (<%= portrait_painting.year %>)</h3>
                <p><%= humanized_money_with_symbol(portrait_painting.price) %></p>
                <p><%= portrait_painting.height %>cm x <%= portrait_painting.width %>cm.
                <p><%= portrait_painting.description.truncate_words(10) %></p>

              <!-- <h2 class="card-painting-pricing"><%= portrait_painting.price %></h2> -->
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>


  <div class="other-paintings d-none">
    <% if @paintings_other %>
      <% @paintings_other.each do |other_painting| %>
        <%= link_to painting_path(other_painting) do %>
            <div class="card-painting">
              <%#= image_tag("Alex-2014.jpg") %>
              <%= image_tag other_painting.photo, crop: :fill %>
              <div class="card-painting-infos">

                  <h3><strong><%= other_painting.name %></strong> (<%= other_painting.year %>)</h3>
                  <p><%= humanized_money_with_symbol(other_painting.price) %></p>
                  <p><%= other_painting.height %>cm x <%= other_painting.width %>cm.
                  <p><%= other_painting.description.truncate_words(10) %></p>

                <!-- <h2 class="card-painting-pricing"><%= other_painting.price %></h2> -->
              </div>
            </div>
        <% end %>
      <% end %>
    <% end %>
  </div>


</div>

app/views/paintings/show.html.erb
<div class="show-container">

<%= link_to 'Back to Shop', paintings_path %>
<br>
  <div class="row justify-content-center painting-details ">
      <div class="col-lg-8 col-md-8 col-sm-12 painting-carrousel">
        <%= image_tag @painting.photo %>
        <%#= render 'photocarousel', photos: @painting.photos %>
      </div>

      <div class="col-lg-4 col-md-4 col-sm-12 painting-infos">
        <h2>"<%= @painting.name.capitalize %>", <span class="main-text"><%= @painting.year %></span></h2>,
        <p class="main-text"><%= humanized_money_with_symbol(@painting.price) %></p>
        <hr>
        <p class="main-text"><strong>Style: </strong><%= @painting.category %></p>
        <p class="main-text"><strong>Measurements:</strong> <%= @painting.height %>cm x <%= @painting.width %>cm</p>
        <p class="main-text"><strong>Description:</strong> <%= @painting.description %></p>

        <%= link_to 'Purchase this painting', new_address_path, { :id => "show-form-button", :class => "nav-link button-primary", 'data-toggle' => 'modal', 'data-target' => '#new-address' } %>

      </div>
      <%= render "addresses/new", painting: @painting %>
  </div>


  <div class="row justify-content-center painting-reviews">
    <div class="col-lg-12 col-md-12 col-sm-12">
      <p class="reviews-title"><strong>Comments</strong></p>
      <hr>
      <!-- <p class="reviews-statement">What do you think of <%#= @painting.name %>?</p> -->

      <% if @painting.reviews.count != 0 %>
          <div id="reviews">
            <% @painting.reviews.each do |review| %>
            <p class="main-text"> "<%= review.content %>"</p>
            <% end %>
          </div>
      <% else %>
          <div >
            <p class="main-text">My painting "<%= @painting.name %>" doesn't have any comments yet...</p>
            <p class="main-text">Feel free to add yours! &#129419</p>
          </div>
      <% end %>

      <button class="button-secondary"><%= link_to 'Leave a comment', new_painting_review_path(@painting), { :class => "button-secondary", 'data-toggle' => 'modal', 'data-target' => '#new-review-modal' } %></button>

      <%= render "reviews/new", review: @review, painting: @painting %>
    </div>

  </div>

</div>