config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "pages#home"

  get "contact", to: 'pages#contact', as: "contact"
  get "inspiration", to: 'pages#inspiration', as: "inspiration"

  get "privacy", to: 'pages#privacy', as: "privacy"
  get "returnpolicy", to: 'pages#returnpolicy', as: "returnpolicy"
  get "sitemap", to: 'pages#sitemap', as: "sitemap"



  resources :paintings do
    resources :reviews, only: [:new, :create]
    resources :orders, only: [:new, :create, :edit, :update, :show] do
      resources :payments, only: [:new, :create]
    end
    # get ''
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

  resources :addresses, only: [:new, :create, :destroy]
  resources :shipping_addresses, only: [:new, :create, :destroy]
  resources :contacts, only: [:new, :create]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    This footer is artfully made with <i class="fas fa-heart"></i> by invent@ ltd
  </div>

  <div class="footer-links">

    <div><a href="https://www.facebook.com/AliciasPaintings/"><i class="fab fa-facebook-square"></i></a></div>
    <div><a href="https://www.instagram.com/alicia_ngomo/"><i class="fab fa-instagram"></i></a></div>
    <div><%= link_to 'About', root_path, class: "nav-link" %></div>
    <div><%= link_to 'Return policy', returnpolicy_path %></div>
    <div><%= link_to 'Privacy policy', privacy_path %></div>
    <div><%= link_to 'Sitemap', sitemap_path %></div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <p class="logo">Alicia's Art</p>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "About", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Shop", paintings_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", contact_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My inspiration", inspiration_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My accountccount", "#", class: "dropdown-item" %>
            <%= link_to "My purchases", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>