config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "pages#home"

  get "contact", to: 'pages#contact', as: "contact"
  get "inspiration", to: 'pages#inspiration', as: "inspiration"

  get "privacy", to: 'pages#privacy', as: "privacy"
  get "returnpolicy", to: 'pages#returnpolicy', as: "returnpolicy"
  get "sitemap", to: 'pages#sitemap', as: "sitemap"



  resources :paintings do
    resources :reviews, only: [:new, :create]
    resources :orders, only: [:new, :create, :edit, :update, :show] do
      resources :payments, only: [:new, :create]
    end
    # get ''
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

  resources :addresses, only: [:new, :create, :destroy]
  resources :shipping_addresses, only: [:new, :create, :destroy]
  resources :contacts, only: [:new, :create]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_contact.html.erb
<div class="modal fade" id="contact-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel">Your message for Alicia</h4>
        <button id="close-btn" type="button" class="close button-primary" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag '/contact' do%>
          Email : </br><%= text_field_tag 'email','', class: "form-control" %></br>
          Subject: </br><%= text_field_tag 'subject', '', class: "form-control" %></br>
          Body:<%= text_area_tag 'body', '', class: "form-control"%>
          <br>
          <%= submit_tag "submit",:value => "submit", :class => "btn button-primary" %>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="contact-container">

  <h1 class="main-subtitle">Contact me</h1>
  <br>

  <div class="contact-content">
      <div class="form">
      <p class="main-text">Send me an email</p>
        <%= form_tag contacts_path do%>
          Name: </br><%= text_field_tag 'name', '', class: "form-control" %></br>
          Email : </br><%= text_field_tag 'email','', class: "form-control" %></br>
          Message:<%= text_area_tag 'message', '', class: "form-control"%>
          <br>
          <%= submit_tag "Submit",:value => "Submit", :class => "btn button-primary" %>
        <%end%>
      </div>

      <div class="contact-image">
        <%#= image_tag("Studio28.jpg", id: "contact-image") %>
      </div>
  </div>

</div>

app/views/pages/home.html.erb
<div class="dashboardbanner">
  <div class="container-text">
    <div class="container-text-text">
      <h2>Alicia Ngomo </h2>
      <h1>Original artwork for sale or rent</h1>
      </div>
      <button><%= link_to "Visit shop", paintings_path %></button>
  </div>
</div>

<div class="artist-statement">
  <div class="about-me">
    <h2 class="main-subtitle"> About me</h2>
      <br>
      <p class="main-text">I started painting at a moment in my life where I needed to channel strong emotions.</p>
      <br>
      <p class="main-text">I grew up in Africa and Spain and this has inspired my work in particular my understanding of colour, light and the passion in my themes. Vibrant colour, music and people's feelings, in particular love, are a constant thread in my work. While leading a successful career in business, art has always been a source of peace, and a way to express emotion and creativity beyond what my day to day allows.</p>
      <br>

      <p class="main-text">I paint at home (in London) and every painting is a reflection of a particular emotion inspired by a dream, a scene observed in her commute, a song, an episode of my life, etc...</p>
  </div>

  <div class="about-my-work">
    <%=  image_tag("Studio5.jpg") %>
    <%=  image_tag("Studio14.jpg") %>
    <%=  image_tag("Studio9.jpg") %>
    <%=  image_tag("Studio13.jpg") %>
    <%=  image_tag("Studio10.jpg") %>
    <%=  image_tag("Studio8.jpg") %>
  </div>

  <div class="about-me">
      <br>
    <h2 class="main-subtitle"> My inspiration </h2>
      <br>
      <p class="main-text"> <span id="love">LOVE</span> ♥️... Emotions are the start of each of my paintings. Love in particular, which I believe is the most powerful feeling. Or the pain of its loss, which is equally powerful. My creative process always starts with a strong feeling. Sometimes my own, other times an emotion conveyed by what I see and hear. Stories from other people, photos or dreams are sources of inspiration. I have awaken in the middle of the might to sketch a painting I dreamed about, or been inspired by the expression of somebody sitting in front of me in the tube.</p>
      <br>

      <p class="main-text"> <span id="music">MUSIC</span> 🎶.... Each of my paintings is linked to a song. Music is as much a part of me as each of my feelings. It is how I remember things, my "chest of memories", a soundtrack of souvenirs. Every time I work on a particular piece I use the same song to reproduce the emotional state that inspired it initially. Music creates a space where there is only the painting, the feeling and me.</p>
      <br>

      <p class="main-text"><span id="music">TRAVEL</span> 🌎...Traveling is my other passion and from my travels around the 🌎 I gather inspiration for my paintings too. Some of my paintings are inspired by something I have seen, a sunset in some distant beach or people I met during my travels.</p>
  </div>

  <div class="about-my-work">
    <%=  image_tag("Salsa-2013.jpg") %>
    <%=  image_tag("The-red-lamp-2011.jpg") %>
    <%=  image_tag("Ricardo-and-marta-2017.jpg") %>
    <%=  image_tag("Orchids1-2015.jpg") %>
    <%=  image_tag("Pieces-of-a-lifetime.jpg") %>
    <%=  image_tag("Forever-now-2015.jpg") %>
  </div>

</div>

<div class="contact ">
  <h2 class="main-subtitle-white"> Contact me </h2>
  <br>
  <p class="main-text-white">Thanks for stopping by and I sincerely hope you enjoy my work :) </p>
  <p class="main-text-white">
    Please send me a message if interested in a commission or if you have any questions about my art!
  </p>
  <br>
  <div id="button-contact">
  <%= link_to ('<p>Get in touch!<span class="emoji">&nbsp&#128522<span></p>').html_safe, new_contact_path, { :class => "button-white button-contact nav-link", 'data-toggle' => 'modal', 'data-target' => '#contact-modal'} %>
  </div>
  <div class="alt-contact">
    <p class="small-text">(Or alternatively <a href="mailto:alithiaspaintings@gmail.com?Subject=Painting%20inquiry" target="_top">send me an email)</a></p>
  </div>
  <%= render "contacts/new" %>

</div>

app/views/pages/inspiration.html.erb
<div class="inspiration-container">
  <h1 class="main-subtitle">What inpires my art?</h1>
  <br>
  <p class="main-text">Music, music, music, music... 🎶. Love ♥️. And everything I see during my travels 🌍</p>
  <p class="main-text">As I travel around the world on a year long sabbatical I have gathered lots of emotions and experiences that have inspired my latest pieces of art. I hope you like them!</p>

    <!-- <div class="row">
      <div class="column">
        <%#= image_tag("Abrazame-2010.jpg") %>
        <%#= image_tag("Abrazame-2010.jpg") %>

      </div>
      <div class="column">
        <%#= image_tag("Abrazame-2010.jpg") %>
        <%#= image_tag("Abrazame-2010.jpg") %>

      </div>
      <div class="column">
        <%#= image_tag("Abrazame-2010.jpg") %>
        <%#= image_tag("Abrazame-2010.jpg") %>

      </div>
      <div class="column">
        <%#= image_tag("Abrazame-2010.jpg") %>
        <%#= image_tag("Abrazame-2010.jpg") %>
      </div>
    </div> -->
  <div class="collage-container">
    <div class="collage">
      <%= image_tag("Abstract-study-5-2014.jpg", class: "collage-photo", id: "photo-1") %>
      <%= image_tag("Abrazame-2010.jpg", class: "collage-photo", id: "photo-2") %>
      <%= image_tag("Autumn-2017.jpg", class: "collage-photo", id: "photo-3") %>
      <%= image_tag("Break-of-dawn-2017.jpg", class: "collage-photo", id: "photo-4") %>
      <%= image_tag("Chicago-2007.jpg", class: "collage-photo", id: "photo-5") %>
      <%= image_tag("Color-rapsody-2015.jpg", class: "collage-photo", id: "photo-6") %>
      <%= image_tag("Forever-now-2015.jpg", class: "collage-photo", id: "photo-7") %>
      <%= image_tag("Eternity-2014.jpg", class: "collage-photo", id: "photo-8") %>
    </div>
  </div>

</div>



<!-- Insert gallery of photos form instragram and link to instagram -->

app/views/pages/privacy.html.erb
<div class="main-container">

  <h1 class="main-subtitle">Privacy policy</h1>
  <hr>

  <p class="main-text">IMPORTANT NOTE CONCERNING DATA PROCESSING IN CONNECTION WITH GOOGLE ANALYTICS</p>

  <p class="main-text">This website uses Google Analytics, a web analytics service provided by Google Ireland Limited. If the responsible body for the data processing that occurs via this website has their basis outside of the European Economic area and Switzerland, then the associated Google Analytics data processing is carried out by Google LLC. Google Ireland Limited and Google LLC. will hereinafter be referred to as “Google”.</p>

  <p class="main-text">Google Analytics uses “cookies”, which are text files saved on the site visitor’s computer, to help the website analyze their use of the site. The information generated by the cookie (including the truncated IP address) about the use of the website will normally be transmitted to and stored by Google.</p>

  <p class="main-text">Google Analytics is used exclusively with the extension "_anonymizeIp ()" on this website. This extension ensures an anonymization of the IP address by truncation and excludes a direct personal reference. Via this extension Google truncates the site visitor’s IP address within member states of the European Union or other parties to the Agreement on the European Economic Area. Only in exceptional situations will the site visitor’s full IP address be transmitted to Google servers in the United States and truncated there. The IP address, that is provided by the site visitor’s browser in using Google Analytics will not be merged by Google with other data from Google.</p>

  <p class="main-text">On behalf of the site operator, Google will use the information collected to evaluate the use of the website, to compile reports on website activity and to provide other website and internet related services to the site operator (Art. 6 (1)( f) GDPR). The legitimate interest in data processing lies in the optimization of this website, the analysis of the use of the website and the adaptation of the content. The interests of the users are adequately protected by the pseudonymization of their data.
  </p>
  <p class="main-text">Google LLC. has certified their compliance with the EU-U.S. Privacy Shield Framework and on that basis they provides a guarantee to comply with European data protection law. The data sent and linked to the Google Analytics cookies, e.g. user IDs or advertising IDs will be automatically deleted after 50 months. The deletion of data whose retention period has been reached is done automatically once a month.</p>

  <p class="main-text">The website visitor may refuse the use of cookies by selecting the appropriate settings in their browser. The website visitor can also prevent Google from collecting information (including their IP address) via cookies and processing this information by downloading this browser plugin and installing it: http://tools.google.com/dlpage/gaoptout</p>

  <p class="main-text">The website visitor can prevent data collection via Google Analytics on this website by clicking here. An "Opt-out Cookie" shall then be applied which shall prevent any future collection of the site visitors data when visiting this website.</p>

  <p class="main-text">Further information concerning data processing and use by Google, the settings and deactivation possibilities can be found in the Google Privacy Policy (https://policies.google.com/privacy) as well as in the Google Ads Settings (https://adssettings.google.com/authenticated).</p>

  <h1 class="main-subtitle">RECAPTCHA</h1>
  <p class="main-text">
  We use the reCAPTCHA service provided by Google Inc. (Google) to protect your submissions via internet submission forms on this site. This plugin checks if you are a person in order to prevent certain website functions from being (ab)used by spam bots (particularly comments). This plugin query includes the sending of the IP address and possibly other data required by Google for the Google reCAPTCHA service. For this purpose your input will be communicated to and used by Google. However, your IP address is previously truncated by Google within member states of the European Union or in other states which are party to the agreement on the European Economic Area and is, as such, anonymized. Only in exceptional cases is a full IP address transmitted to a Google server in the United States and truncated there. On behalf of the operator of this website, Google will use this information to evaluate your use of this service. The IP address provided by reCaptcha from your browser shall not be merged with any other data from Google.</p>

  <p class="main-text">This data collection is subject to the data protection regulations of Google (Google Inc.). For more information about Google's privacy policy, please visit: https://policies.google.com/privacy?hl=en
  By using the reCAPTCHA service, you consent to the processing of data about you by Google in the manner and for the purposes set out above.
  </p>
</div>

app/views/pages/returnpolicy.html.erb
<div class="main-container">

  <h1 class="main-subtitle">Return policy and return form</h1>
  <hr>

  <p class="main-text"><strong>Instructions on withdrawal</strong></p>

  <p class="main-text"><strong>Right of withdrawal</strong></p>

  <p class="main-text">You have the right to withdraw from this contract within 30 days without giving any reason. The withdrawal period will expire after 30 days from the day on which you acquire, or a third party other than the carrier and indicated by you acquires, physical possession of the goods.
  </p><p class="main-text">To exercise the right of withdrawal, you must inform me (Email: alicia-art@gmail.com) of your decision to withdraw from this contract by an unequivocal statement (e.g. an e-mail). To meet the withdrawal deadline, it is sufficient for you to send your communication concerning your exercise of the right of withdrawal before the withdrawal period has expired.
  </p>

  <p class="main-text"><strong>Effects of withdrawal</strong></p>

  <p class="main-text">If you withdraw from this contract, I shall reimburse to you all payments received from you, including the costs of delivery (with the exception of the supplementary costs resulting from your choice of a type of delivery other than the least expensive type of standard delivery offered by me), without undue delay and in any event not later than 14 days from the day on which I am informed about your decision to withdraw from this contract. I will carry out such reimbursement using the same means of payment as you used for the initial transaction, unless you have expressly agreed otherwise; in any event, you will not incur any fees as a result of such reimbursement. I may withhold reimbursement until I have received the goods back or you have supplied evidence of having sent back the goods, whichever is the earliest.</p>

  <p class="main-text">You shall send back the goods or hand them over to me, without undue delay and in any event not later than 14 days from the day on which you communicate your withdrawal from this contract to me. The deadline is met if you send back the goods before the period of 14 days has expired. You will have to bear the direct cost of returning the goods. Please avoid damage and contamination of the product. If you decide to exercise the withdrawal, send the goods in the original packaging with all packaging components back to me. Use a protective outer packaging. If you do not have the original packaging, please provide a suitable package for adequate protection against damage in transit. You are only liable for any diminished value of the goods resulting from the handling other than what is necessary to establish the nature, characteristics and functioning of the goods.</p>

</div>

app/views/pages/sitemap.html.erb
<div class="main-container">
  <h1 class="main-subtitle">Sitemap</h1>
  <hr>

    <ul class="main-text">
      <li>About</li>
      <li>Shop</li>
      <li>Contact</li>
      <li>Inspiration</li>
    </ul>

</div>