config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "pages#home"

  get "contact", to: 'pages#contact', as: "contact"
  get "inspiration", to: 'pages#inspiration', as: "inspiration"

  get "privacy", to: 'pages#privacy', as: "privacy"
  get "returnpolicy", to: 'pages#returnpolicy', as: "returnpolicy"
  get "sitemap", to: 'pages#sitemap', as: "sitemap"



  resources :paintings do
    resources :reviews, only: [:new, :create]
    resources :orders, only: [:new, :create, :edit, :update, :show] do
      resources :payments, only: [:new, :create]
    end
    # get ''
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

  resources :addresses, only: [:new, :create, :destroy]
  resources :shipping_addresses, only: [:new, :create, :destroy]
  resources :contacts, only: [:new, :create]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/shipping_addresses_controller.rb
class ShippingAddressesController < ApplicationController

  def new
    @shipping_address = Shippingaddress.new
  end

  def create
    @painting = Painting.find(params[:shippingaddress][:painting_id])
    @shipping_address = Shippingaddress.new(shipping_params)
    @shipping_address.user = current_or_guest_user
    if @shipping_address.save!
      redirect_to new_painting_order_path(@painting, shipping_address_id: @shipping_address.id)
    else
      render 'shipping_addresses/new'
    end
  end

  private

  def shipping_params
    params.require(:shippingaddress).permit(:shipping_address, :shipping_country, :shipping_zipcode,
      :shipping_city, :shipping_comments)
  end
end

app/views/shipping_addresses/new.html.erb
<script>
window.addEventListener('load', (event) => {
  console.log('page is fully loaded');
  const modal = document.querySelector('#new-shipping');
  console.log(modal);
  modal.classList.add('show');
  modal.classList.add('modal-new');
});
</script>

<div class="modal modal-new fade" id="new-shipping" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title purple-title" id="exampleModalLabel"> Where shall I ship your painting? </h4>
        <button type="button" class="close close-btn" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="billing-details form-group">

           <%= form_for @shipping_address, :url => shipping_addresses_path, method: :post do |f| %>
              <%= f.hidden_field :painting_id, :value => params[:painting_id] %>
              <%= f.hidden_field :shipping_address_id, :value => @shipping_address.id %>
              <%= f.text_field :shipping_address, id: "shipping_address", placeholder: "Full address", class: 'form-control'%><br>
              <%= f.number_field :shipping_zipcode, id: "shipping_zipcode", placeholder: "Zip code", class: 'form-control'%><br>
              <%= f.text_field :shipping_city, id: "shipping_city", placeholder: "City", class: 'form-control'%><br>
              <%= f.text_field :shipping_country, id: "shipping_country", placeholder: "Country", class: 'form-control'%><br>
              <%= f.text_field :shipping_comments, id: "shipping_comments", placeholder: "Any shipping instructions?", class: 'form-control'%><br>
              </div>

              <%= f.submit :"Save shipping address", id: "submit-btn", class: "button-primary" %>
            <% end %>
        </div>

      </div>
    </div>
  </div>
</div>